apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: athorne
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/athorne-harbor-project/app@sha256:9bdc65cbd7a2a15ec2b3d660928271b2857e36066569b91b995b93add63bc472
        ports:
        - containerPort: 5000
