apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: athorne
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image:  harbor.dev.afsmtddso.com/athorne-harbor-project/db@sha256:10025c538a2df140369daa01767ca95150d0feeed497e72edbe62efe2f82b435
        ports:
        - containerPort: 5432
